version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: docker_manager_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/backend:/app
      - /app/node_modules # This is to avoid the local node_modules overwriting the container's
    environment:
      - NODE_ENV=development
    networks:
      - docker_manager_network

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      target: build
    container_name: docker_manager_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    command: ["npm", "start"]
    networks:
      - docker_manager_network
    depends_on:
      - backend

networks:
  docker_manager_network:
    driver: bridge
